# Generated by Django 4.0.4 on 2025-01-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asanatask',
            options={'managed': True},
        ),
    ]
