repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort
        name: isort (python import sorter)
        language_version: python3

  - repo: https://github.com/pre-commit/flake8
    rev: v6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8==6.0.0]
