# docker-compose.yml
version: '3.8'

services:
  sa_stairs_web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - sa_stairs_db

  sa_stairs_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sa_stairs_data:/var/opt/mssql
    command: >
      bash -c '
      /opt/mssql/bin/sqlservr &
      sleep 30 &&
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Password123 -Q "CREATE DATABASE sa_stairs_db"
      tail -f /dev/null
      '

volumes:
  sa_stairs_data: