services:
  sastairs_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db

  sastairs_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Str0ngP@ssw0rd!
      - MSSQL_PID=Express
      - MSSQL_USER=sa
      - MSSQL_DB=job_tracking_dev_dump_01

    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1433:1433"
    env_file:
      - .env.prod

volumes:
  static_volume:
  mssql_data: