version: '3.8'

services:
  sastairs_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8100
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8100:8100"
    env_file:
      - .env.prod
    depends_on:
      sastairs_db:
        condition: service_healthy

  sastairs_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Str0ngP@ssw0rd!
      - MSSQL_PID=Express
      - MSSQL_USER=sa
      - MSSQL_DB=job_tracking_dev_dump_01
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1433:1433"
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Str0ngP@ssw0rd! -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  static_volume:
  mssql_data:
