version: '3.8'

services:
  sastairs_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8100
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8100:8100"
    env_file:
      - .env
    networks:
      - sastairs_network

networks:
  sastairs_network:
    driver: bridge

volumes:
  static_volume:
