services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8100"]
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8100:8100"
    env_file:
      - .env.prod

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env.prod

volumes:
  static_volume:
  postgres_data:
