# docker-compose.yml
version: '3.8'

services:
  sastairs_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8100
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8100:8100"
    env_file:
      - .env.prod
    depends_on:
      sastairs_db:
        condition: service_healthy
    networks:
      - sastairs_network

  sastairs_db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Str0ngP@ssw0rd!
      - MSSQL_PID=Express
      - MSSQL_USER=sa
      - MSSQL_DB=job_tracking_dev
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Str0ngP@ssw0rd!" -Q "SELECT 1" || exit 1
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - sastairs_network

networks:
  sastairs_network:
    driver: bridge

volumes:
  static_volume:
  mssql_data: