services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: "your_django_secret_key_here"
      DJANGO_DEBUG: "True"
      DATABASE_NAME: "master"
      DATABASE_USER: "sa"
      DATABASE_PASSWORD: "Str0ngP@ssw0rd!"
      DATABASE_HOST: "db"
      DATABASE_PORT: "1433"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Str0ngP@ssw0rd!"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P Str0ngP@ssw0rd! -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  static_volume:
  mssql_data:
