# Generated by Django 4.0.4 on 2024-12-09 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_first_name', models.CharField(max_length=255)),
                ('contact_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_pref_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'QUOTING_SYSTEM_DB].[CONTACT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('hr_id', models.AutoField(primary_key=True, serialize=False)),
                ('hr_job_title', models.CharField(max_length=100)),
                ('hr_guid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('hr_pin', models.CharField(blank=True, max_length=128, null=True)),
                ('hr_timesheet_user', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'HR_SYSTEM].[HUMAN_RESOURCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactoryAppDevices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('api_key', models.CharField(max_length=50, unique=True)),
                ('api_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'HR_SYSTEM].[Factory_App_Devices',
                'managed': True,
            },
        ),
    ]
