name: Deploy Django App to EC2 on Staging Push

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /path/to/your/django/project
          git pull origin staging
          # Install dependencies (if needed)
          docker-compose down
          docker-compose up -d --build
        EOF

    - name: Run Django migrations
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /path/to/your/django/project
          docker-compose exec web python manage.py migrate
        EOF

    - name: Collect static files
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /path/to/your/django/project
          docker-compose exec web python manage.py collectstatic --noinput
        EOF

    - name: Restart EC2 services
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo systemctl restart your-service
        EOF
